DELETE http://localhost:3001/api/persons/62597607c83a55c616149b33

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Olabod Bidmus",
    "number": "081-6135672"
}